# Generated by Django 6.0.7 on 2026-08-04 13:06

from django.db import migrations, models


def create_head_role(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")

    Role.objects.update_or_create(
        code="head",
        defaults={
            "name": "Head",
        },
    )


def remove_head_role(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")

    Role.objects.filter(
        code="head",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("employee", "Employee"),
                    ("manager", "Manager"),
                    ("head", "Head"),
                    ("administrator", "Administrator"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.RunPython(
            create_head_role,
            remove_head_role,
        ),
    ]