# Generated by Django 6.0.7 on 2026-07-28 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Проект / Стрим')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Проект / Стрим',
                'verbose_name_plural': 'Проекты / Стримы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('code', models.SlugField(help_text='Технический код статуса, например: in-progress', unique=True, verbose_name='Код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='Краткое описание того, что необходимо сделать', max_length=500, verbose_name='Описание')),
                ('external_number', models.CharField(blank=True, help_text='Например: RND-1234', max_length=100, verbose_name='Номер')),
                ('external_url', models.URLField(blank=True, help_text='Например, ссылка на задачу в YouTrack', max_length=500, verbose_name='Ссылка на внешнюю задачу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project_stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tracker.projectstream', verbose_name='Проект / Стрим')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tracker.taskstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Требования, Прототип, API-документация', max_length=200, verbose_name='Название')),
                ('url', models.URLField(max_length=1000, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_task_artifacts', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='tracker.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Артефакт задачи',
                'verbose_name_plural': 'Артефакты задач',
                'ordering': ['created_at'],
            },
        ),
    ]
