# Generated by Django 6.0.7 on 2026-07-30 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWeeklyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Дата понедельника соответствующей недели', verbose_name='Начало недели')),
                ('text', models.TextField(blank=True, verbose_name='Еженедельный статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_statuses', to='tracker.task', verbose_name='Задача')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_weekly_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Еженедельный статус задачи',
                'verbose_name_plural': 'Еженедельные статусы задач',
                'ordering': ['-week_start'],
                'constraints': [models.UniqueConstraint(fields=('task', 'week_start'), name='unique_task_weekly_status')],
            },
        ),
    ]
