# Generated by Django 6.0.7 on 2026-08-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_bsa_department'),
        ('tracker', '0002_taskweeklystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='accounts.department', verbose_name='Отдел'),
        ),
    ]
