# Generated by Django 6.0.7 on 2026-08-04 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_department'),
        ('tracker', '0004_assign_bsa_department_to_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='accounts.department', verbose_name='Отдел'),
        ),
    ]
